contract-name: mtdhoxhyphaa
doc-table-name: documents
edge-table-name: edges
firehose-endpoint: telostest.firehose.eosnation.io:9000
dfuse-api-key: dc6087c88050f3caeed46f22767c357c
dfuse-auth-url: https://auth.eosnation.io
eos-endpoint: https://testnet.telos.caleos.io
dgraph-alpha-host: localhost
dgraph-alpha-grpc-port: 9080
dgraph-alpha-http-port: 8080
prometheus-port: 2114
start-block:  
heart-beat-frequency: 100
elastic-endpoint: https://hypha.es.eu-west-1.aws.found.io:9243/dho-testnet-documents/_search
elastic-api-key: ZE0***
type-mappings:
  - type: vote.tally
    labels:
      fail:
        - vote_power
      pass:
        - vote_power
custom-interfaces:
  - name: Votable
    fields:
      - name: expiration
        type: time_point
        content-group: ballot
        signature: true
      - name: title
        type: string
        content-group: details
      - name: description
        type: string
        content-group: details
      - name: vote
        type: vote
      - name: votetally
        type: vote.tally
    types:
      - payout
      - assignment
      - assignbadge
      - edit
      - suspend
logical-ids:
  - type: member
    ids:
      - content-group: details
        name: member
        type: name
  - type: dao
    ids:
      - content-group: details
        name: dao_name
        type: name
  - type: dho
    ids:
      - content-group: details
        name: root_node
        type: name
