contract-name: dao.hypha
doc-table-name: documents
edge-table-name: edges
firehose-endpoint: localhost:9000
eos-endpoint: https://telos.caleos.io
dgraph-alpha-host: localhost
dgraph-alpha-grpc-port: 9080
dgraph-alpha-http-port: 8080 
prometheus-port: 2114
start-block: 136860100
heart-beat-frequency: 100
dfuse-jwt: server_eeb2882943ae420bfb3eb9bf3d78ed9d
type-mappings:
- type: VoteTally
  labels:
    pass:
      - vote_power
    fail:
      - vote_power
custom-interfaces:
  - name: Votable #New type so use name to use in GQL
    fields:
      - content-group: ballot
        name: expiration
        type: time_point
        signature: true # used to identify votable types
      - content-group: details
        name: title
        type: string
        is-id: true
      - content-group: details
        name: description
        type: string
      - name: vote
        type: vote
      - name: votetally
        type: vote.tally
    types:
      - payout
      - assignbadge
  - name: User
    fields:
      - content-group: details
        name: profile
        type: checksum256
        signature: true
      - content-group: details
        name: account
        type: name
        signature: true
  - name: Extendable #New type so use name to use in GQL
    fields:
      - content-group: details
        name: extension_name
        type: string
        signature: true
      - name: extension
        type: document
  - name: Taskable #New type so use name to use in GQL
    fields:
      - content-group: details
        name: task
        type: string
      - name: user
        type: user
    types:
      - admin.task
  - name: Editable #New type so use name to use in GQL
    fields:
      - content-group: details
        name: version
        type: string
    types:
      - admin.task
      - payout
logical-ids:
  - type: member #Existing type use name from orginal chain doc
    ids:
      - content-group: details
        name: member
        type: name
  - type: dho #Existing type use name from orginal chain doc
    ids:
      - content-group: details
        name: root_node
        type: name