contract-name: dao.hypha
doc-table-name: documents
edge-table-name: edges
firehose-endpoint: localhost:9000
eos-endpoint: https://telos.caleos.io
dgraph-alpha-host: localhost
dgraph-alpha-grpc-port: 9080
dgraph-alpha-http-port: 8080
prometheus-port: 2114
start-block: 136860100
heart-beat-frequency: 100
dfuse-jwt: server_eeb2882943ae420bfb3eb9bf3d78ed9d
custom-interfaces:
  - name: Votable #New type so use name to use in GQL
    fields:
      - content-group: ballot
        name: expiration
        type: time_point
        signature: true # used to identify votable types
      - content-group: details
        name: title
        type: string
        is-id: true
      - content-group: details
        name: description
        type: string
      - content-group: system
        name: hash
        type: checksum256
      - name: vote
        type: vote
      - name: votetally
        type: vote.tally
  - name: User
    fields:
      - content-group: details
        name: profile
        type: profile.data
        signature: true
      - name: member_name
        type: name
        signature: true # used to identify votable types
    types:
      - owner
      - admin
  - name: Editable
    fields:
      - content-group: details
        name: version
        type: string
    types:
      - pro.paper
